### ISSUE TITLE
Development environment using devcontainer

### ISSUE THREAD

**Issue by xec-abailey** [zauberzeug/nicegui#1018]
@xec-abailey instructions for devcontainer setup in [CONTRIBUTING.md](https://github.com/zauberzeug/nicegui/blob/main/CONTRIBUTING.md) would be great. We are not using them very actively our self but there is much value for the community. Are you willing to create a pull request?

_Originally posted by @rodja in https://github.com/zauberzeug/nicegui/issues/1014#issuecomment-1586585280_
            
Allowing the development environment to be opened inside of a [devcontainer](https://code.visualstudio.com/docs/devcontainers/containers) would give a much easier developer setup and prevent misalignment between developers. 

After completion the dev can clone the repo locally as normal, or can use the "Dev Containers: Rebuild and Reopen in Container" task in vscode (ctrl-shift-p) which will build to the defined target/dockerfile (in this case development.Dockerfile). Also the user can open the repo directly from github through Codespaces which will also spin up a remote instance and build the development container there. 

### Tasks
- [x] add devcontainer.json to .devcontainer folder in repo
- [x] build from development.Dockerfile

**Comment by jacoverster** [comment]
Hey @xec-abailey , I'm up for this, I use devcontainers daily.

**Comment by jacoverster** [comment]
I noticed that the autopep8 extension in nicegui.code-workspace is deprecated, would you be interested in replacing it with official autopep8 extension from Microsoft?

![image](https://github.com/zauberzeug/nicegui/assets/22006760/b0e08fe2-1224-4a8c-bc65-4d725763b6b7)

**Comment by xec-abailey** [comment]
I've been poking it, but as a new contributor to this project I don't know the dev environment as well so I'm being pretty cautious about the changes I'm making. I do have lots of experience with devcontainers and python, poetry, docker etc dev environments and I see plenty of efficiencies to be gained here. 

Mainly the end goal of the following would be to allow contributors to get into dev context with almost no effort (my laziness factor coming into play there). Also think adding in automated PR testing would be nice at the same time since it's not a huge amount of additional work. Happy to advise in any capacity that is helpful. 

- [ ] I see that the requirements.txt in tests are mostly incorporated into pyproject.toml dev group, I would go ahead and add the rest of them in there, coupled with
- [ ] multi-stage dockerfile with base, dev, test stages. 
- [ ] **Base** should install base poetry environment as well as system dependencies (poetry command = `poetry install --without=dev --no-root`) 
- [ ] **Test** should extend base and install necessary test environment deps `poetry install --group dev --no-root`. This would be used for the test CI rather than installing directly on the github runner. Essentially replacing all of test.yml workflow with a build stage to the test target of the dockerfile . Then add an entrypoint that runs pytest for target folder - should be easy enough to slot this in and then 
- [ ] Add PR trigger for testing something to the effect of the below for ci
```yaml
on:
  pull_request:
    branches: ["main"]

# only allow one job to run at a time for this PR
concurrency:
  group: ${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true
```
- [ ] **Development** should extend base stage and add full installation of poetry (should be the same as the current development.dockerfile). Minus the entrypoint CMD 
- [ ] Devcontainer.json created that targets Development stage of dockerfile, includes extensions in customizations.vscode.extensions. I typically do away with workspaces at that point but some people like them 

I'd say the above shouldn't be too bad and provide a much smoother contributor experience. At this point the contributor workflow would be one of two paths: 

1) Clone repo, reopen in dev container, dev container builds to development target, opens in container with everything setup
2) Open in codespace, codespace builds and opens container 

Other random stuff: 

- [My recent PR ](https://github.com/zauberzeug/nicegui/pull/1014) I got the comment that the quote formatting was wrong, wondering if the formatting rules can be locked down to prevent this.
- mypy.ini and pytest.ini can be condensed into pyproject.toml (really not a huge deal but it cuts down on confusion with many configs in root - helpful for less experienced contributors imo)
- Release and fly dockerfiles probably could be condensed into a multi-stage file as well if desired, maybe some release CI efficiencies after that but I'd need to dig into it a bit more and understand the deployment targets better
- Can add pre-commit to enforce formatting or whatever else

**Comment by rodja** [comment]
> I noticed that the autopep8 extension in nicegui.code-workspace is deprecated, @rodja would you be interested in replacing it with official autopep8 extension from Microsoft?

@jacoverster Yes that would be very helpful. Happy to receive a pull request to fix that :-)

**Comment by rodja** [comment]
Wow, @xec-abailey your checklist looks super cool. Please go ahead. A multi-stage build which gets rid of all our duplications is really needed. About you other "random stuff":

- Locking down the formatting rules would be great (via pre-commit hook for example). Can you start a draft pull request and we discuss the details there.
- We are happy for all condensations possible (eg. mypy.ini + pytest.ini -> pyproject.toml), please create a pull request so we can try it out :-)
- `fly.dockerfile` is used to deploy code to https://nicegui.io. We build it separately from the `release.dockerfile` because there are (rare) cases where we want to push non-officially-released code (eg. hotfixes) to fly.io.

**Comment by jacoverster** [comment]
@xec-abailey your list looks great, I'm also a fan of multi-stage docker with my devcontainers. Let me know if you need help on any of it or if you want to connect and work on it together, keen to help where I can. 👍🏻

**Comment by xec-abailey** [comment]
> @xec-abailey your list looks great, I'm also a fan of multi-stage docker with my devcontainers. Let me know if you need help on any of it or if you want to connect and work on it together, keen to help where I can. 👍🏻

Going to try and get this finished up early part of this week, will certainly add you as a reviewer and any feedback is appreciated!

**Comment by xec-abailey** [comment]
@rodja @jacoverster https://github.com/zauberzeug/nicegui/pull/1057 making some progress, check it out if you like

**Comment by falkoschindler** [comment]
I'll close this issue as completed in PR #1532.
Thanks again, @xec-abailey and @jacoverster! 🎉
